# Generated by Django 4.0 on 2022-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=500)),
                ('phn_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('key_skills', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=10)),
                ('adhaarnum', models.IntegerField()),
                ('reg_data', models.CharField(max_length=30)),
            ],
        ),
    ]
