# Generated by Django 4.0 on 2022-01-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='key_skills',
            new_name='keyskills',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phn_num',
            new_name='phnnum',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='reg_data',
            new_name='regdate',
        ),
        migrations.AlterField(
            model_name='registration',
            name='adhaarnum',
            field=models.CharField(max_length=12),
        ),
    ]
