# Generated by Django 4.0 on 2022-01-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_rename_key_skills_registration_keyskills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='keyskills',
            new_name='skills',
        ),
    ]
