# Generated by Django 4.0 on 2022-01-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0004_rename_keyskills_registration_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
    ]
