# Generated by Django 4.0.4 on 2022-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0006_adminlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='userId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
